### ISSUE TITLE
几个反馈

### ISSUE THREAD

**Issue by maplefz** [YohoYang/VSGUI#2]
一些小小的压制菜鸟的反馈
系统环境：笔记本，CPU：AMD-4800H，GPU：GTX2060，16G内存，系统：windows10 21H2
出现问题：1、点击“编辑器预览”软件会直接闪退，没有任何错误窗口提示。即使是刚打开软件没有放入任何文件时都会直接闪退。（后来点击“编辑器预览”又正常了）
2、一直使用megui，没有使用过VS Editor，请问有megui那样的“avs cutter”图形化cut功能？
3、使用smart cutter软件处理导出的ts文件，通过智能解流功能只能导出m2v文件，没有导出音频文件，不知是否相关解码器的限制。
4、压制速度：测试了几个不同大小的ts文件，均为使用智能解流功能后，通过简易压制模式进行，视频解码参数为标准H264，视频分辨率为720P
			文件1：2.5G，压制速度正常，表现为90-100fps
			文件2：6G，压制速度平均50-60fps左右，使用megui压制（已反交错，模式x264 scratchpad,encoding mode:const quality,质量：22）为100fps左右
			文件3：12.2G，压制速度平均50-60fps左右，使用megui压制与文件2情况类似

**Comment by YohoYang** [comment]
1、编辑器预览闪退的问题没有复现，后面还会的话再观察一下
2、没有类似的功能，但使用其实一样很简单。简略教程：使用VS Editor打开脚本，先处理好交错，然后进行预览，此时可以获得反交错后的帧（左下角）。然后在反交错代码或者是最后一行video.set_output()前面加上剪切脚本，格式大致如下，写好后再一次预览就可以看到剪切后的效果了，对这一行前面写个#就可以注释掉。
`video = core.std.Trim(video, 490, 2646)+core.std.Trim(video, 6245, 23337)`
3、没有用过smart cutter，导出后的视频不知道是不是本来就没有音频，如果有的话，可能要处理一下兼容性，有空我找个来试试。
4、压制速度的话，和VSGUI关系其实不大，GUI只是帮忙把任务发给vapoursynth。在我的使用体验下，感觉和输入的文件大小应该没什么关系，主要是和megui相比，压制参数和脚本里使用的滤镜是不是相同；还有是两边显示的即时帧率可能算法不同，不知道是不是压制完成后的总耗时就是有差别。当然，vapoursynth里也有一些没有兼容多线程的滤镜，可能还需要自己多通过控制变量来检查（现在附进去的几个都是测过的，性能不错）
