### ISSUE TITLE
NVENC编码器报错 不管是什么文件都是这样报错

### ISSUE THREAD

**Issue by GDZJS** [YohoYang/VSGUI#24]
环境:
Win11
GPU0 RTX 4060 LAPTOP 
GPU1 AMD Radeon 780M Graphics
已经在系统设置中将编码器和GUI选择GPU0运行
[2024-05-07 21:03:36] Input file is not specified.
[2024-05-07 21:03:37] Error: fwrite() call failed when writing frame: 0, plane: 0, errno: 22

**Comment by YohoYang** [comment]
啊啊非常抱歉，通过网络获取的连接参数有误，这里的设置应该多加上 -i -，原来从1.0.0版本开始就一直有错。
现在已经修改了内置的这个参数。应该已经可以使用了，如果没有修改设置的话，应该重新启动软件后就会自动拉取到更新，也可以自己修改自己的自定义编码器设置来解决。
![图片](https://github.com/YohoYang/VSGUI/assets/16574473/88bbe35c-fa5a-49ef-bbf0-64bcb721bc2b)
