### ISSUE TITLE
希望能用mediainfo检测如果文件自封（内挂）字幕 可以提示并直接读取压制

### ISSUE THREAD

**Issue by GDZJS** [YohoYang/VSGUI#25]

**Comment by GDZJS** [comment]
在当前版本 需要将内封的字幕提取出来后才能压制

**Comment by YohoYang** [comment]
虽然听起来确实是很方便（  但真的这么懒吗x，也就多解流一下就行
如果要这样处理也只能读取第一个字幕，多字幕的情况下没办法那么智能

**Comment by GDZJS** [comment]
主要是像是Shana一类的 会默认以内挂的第一个字幕压制 也可以单独选择 现在好多字幕组只给一个rawbd+内挂 如果能批量智能压制会帮大忙！麻烦您了 如果没有计划也没有关系

**Comment by YohoYang** [comment]
> 主要是像是Shana一类的 会默认以内挂的第一个字幕压制 也可以单独选择 现在好多字幕组只给一个rawbd+内挂 如果能批量智能压制会帮大忙！麻烦您了 如果没有计划也没有关系

可以考虑加，但可能不会那么快，你先用着（
