### ISSUE TITLE
python版本及vapoursynth 版本是否可以使用自己的版本

### ISSUE THREAD

**Issue by Rio-Futaba** [YohoYang/VSGUI#3]
初步尝试使用，使用软件中的reopgui 安装havsfunc 插件。运行时提示缺少vsutil。无法从源代码安装vsutil

**Comment by YohoYang** [comment]
关于使用自己系统安装的python和vapoursynth版本：
后续更新中会加上一个设置项，但需要一段时间测试

安装havsfunc后缺少vsutil的情况：
可以的话麻烦提供一下vpy脚本内容，方便查错。
（因为我自己的压制过程中并没有用到havsfunc，所以可能有没发现的问题）

**Comment by Rio-Futaba** [comment]
您好 我已自行解决此问题。已单独安装和您提供版本一致的python和vapoursynth 版本后，安装vsutil并提取出来放到本程序目录下

**Comment by YohoYang** [comment]
> 您好 我已自行解决此问题。已单独安装和您提供版本一致的python和vapoursynth 版本后，安装vsutil并提取出来放到本程序目录下

解决了就好，不过我也确实想知道你说的vsutil是指哪些文件，从哪里安装，了解后我可以集成到版本里，这样其他人用起来也方便

**Comment by Rio-Futaba** [comment]
麻烦你提供一下邮箱 我打包发给你

**Comment by YohoYang** [comment]
> 麻烦你提供一下邮箱 我打包发给你

可以，邮箱是yohoyang@outlook.com
当然，github这里直接拖进来也可以上传

**Comment by Rio-Futaba** [comment]
[vsutil-0.7.0.zip](https://github.com/YohoYang/VSGUI/files/8937174/vsutil-0.7.0.zip)
关闭了也可以上传 我已上传到这里

**Comment by YohoYang** [comment]
辛苦了~

**Comment by Rio-Futaba** [comment]
这个要放到bin/vs/python 目录下即可

**Comment by YohoYang** [comment]
> 这个要放到bin/vs/python 目录下即可

是不是只需要vsutil文件夹下的clips.py、func.py、info.py、types.py四个脚本放到\bin\vs\python\libs里就行，回头我试试，有没有vpy脚本的例子，给一份，我测试测试

**Comment by Rio-Futaba** [comment]
我现在手头也没有. 你直接import havsfunc 然后运行应该就会出错 如果没有放进去这个的话

**Comment by YohoYang** [comment]
噢，直接import就会报错了吗，那好测。
我找时间看看

**Comment by YohoYang** [comment]
已经支持直接使用系统的Py和vs  [v0.3.0](https://github.com/YohoYang/VSGUI/releases/tag/v0.3.0)

**Comment by hooke007** [comment]
vsutil 有多种安装方式
- 直接 `pip install vsutil` 完事
- 把它仓库的子文件目录 [vsutil](https://github.com/Irrational-Encoding-Wizardry/vsutil/tree/master/vsutil) 拖进 `site-packages` 完事

**Comment by YohoYang** [comment]
> vsutil 有多种安装方式
> 
>     * 直接 `pip install vsutil` 完事
> 
>     * 把它仓库的子文件目录 [vsutil](https://github.com/Irrational-Encoding-Wizardry/vsutil/tree/master/vsutil) 拖进 `site-packages` 完事

嗯嗯，现在内置的环境已经把vsutil集成了。
