### ISSUE TITLE
几个用户操作优化建议

### ISSUE THREAD

**Issue by zdrzdr** [YohoYang/VSGUI#4]
1，编辑编码器参数之后，处理视频的编码器会变为默认的配置参数
2，编辑编码器参数的时候，如果自动切换到当前设置的编码器会方便很多
3，编码器参数如果复制粘贴多行，只会保留第一行
4，增加一个视频参数查看的页面，拖进来查看视频参数，感觉很方便

**Comment by YohoYang** [comment]
1、2：是因为简易压制和高级压制的参数设置没有同步，编辑界面默认读取了高级压制的设置，后续可以优化一下。
3：参数是不支持换行的，每个设置之间通过空格分隔。如果有需要换行的例子可以贴个例子看看。
4：这个的话类似于mediainfo，可以考虑加，但最近暂时还不考虑x，现在很多视频播放器都可以查看，也可以直接安装一个mediainfo软件配合使用x

**Comment by zdrzdr** [comment]
> 1、2：是因为简易压制和高级压制的参数设置没有同步，编辑界面默认读取了高级压制的设置，后续可以优化一下。 3：参数是不支持换行的，每个设置之间通过空格分隔。如果有需要换行的例子可以贴个例子看看。 4：这个的话类似于mediainfo，可以考虑加，但最近暂时还不考虑x，现在很多视频播放器都可以查看，也可以直接安装一个mediainfo软件配合使用x

恩，主要还是1，2改配置的操作
3，不是很需要，就是单纯的复制文档里别人的参数用到了一下。
4，确实也只是个甜品功能

**Comment by YohoYang** [comment]
v0.3.4
