### ISSUE TITLE
请问GUI可以同时把水印一起压制进视频吗？

### ISSUE THREAD

**Issue by OKtheMirror** [YohoYang/VSGUI#7]
如果可以求操作方法指导

**Comment by YohoYang** [comment]
可以使用aegisub软件制作一个水印ass字幕，然后压制时添加这个字幕文件。
可以随你的需要来制作这个水印字幕文件，会动的或者是透明的等等都可以实现。

**Comment by YohoYang** [comment]
> > 可以使用aegisub软件制作一个水印字幕，然后压制时添加这个字幕文件。 可以随着你的需要来制作这个水印字幕文件，会动的或者是透明的等等都可以实现。
> 
> 可VSGUI支持同时压制两个ASS文件到一个视频中吗？

可以，已经做了，这几天就更新新版本

**Comment by OKtheMirror** [comment]
> > > 可以使用aegisub软件制作一个水印字幕，然后压制时添加这个字幕文件。可以当你的需要来制作这个水印字幕文件时，会动的或者是透明的等等都可以实现。
> > 
> > 
> > VSGUI可以支持同时压制两个ASS文件到一个视频中吗？
> 
> 可以，已经做到了，这几天就更新新版本

那太好了，期待新版本

**Comment by YohoYang** [comment]
> > > > 可以使用aegisub软件制作一个水印字幕，然后压制时添加这个字幕文件。可以当你的需要来制作这个水印字幕文件时，会动的或者是透明的等等都可以实现。
> > > 
> > > 
> > > VSGUI可以支持同时压制两个ASS文件到一个视频中吗？
> > 
> > 
> > 可以，已经做到了，这几天就更新新版本
> 
> 那太好了，期待新版本

但其实如果会写vpy脚本的话，使用高级压制现在也可以（  
vpy也还能做到很多其他的事情，比如裁剪、去黑边等等

**Comment by YohoYang** [comment]
> > > > 可以使用aegisub软件制作一个水印字幕，然后压制时添加这个字幕文件。可以当你的需要来制作这个水印字幕文件时，会动的或者是透明的等等都可以实现。
> > > 
> > > 
> > > VSGUI可以支持同时压制两个ASS文件到一个视频中吗？
> > 
> > 
> > 可以，已经做到了，这几天就更新新版本
> 
> 那太好了，期待新版本

已更新，现在支持简易压制批量输入https://github.com/YohoYang/VSGUI/releases/tag/v1.0.0

**Comment by OKtheMirror** [comment]
> > > > > 可以使用aegisub软件制作一个水印字幕，然后压制时添加这个字幕文件。可以当你的需要来制作这个水印字幕文件时，会动的或者是透明的等等都可以实现。
> > > > 
> > > > 
> > > > VSGUI可以支持同时压制两个ASS文件到一个视频中吗？
> > > 
> > > 
> > > 可以，已经做到了，这几天就更新新版本
> > 
> > 
> > 那太好了，期待新版本
> 
> 已更新，现在支持简易压制批量输入https://github.com/YohoYang/VSGUI/releases/tag/v1.0.0

出大事了，更新完之后现在一压制就报错，这怎么办啊
