### ISSUE TITLE
那个添加多个ASS字幕文件的功能有BUG啊

### ISSUE THREAD

**Issue by OKtheMirror** [YohoYang/VSGUI#9]
我打了分隔符号，然后每次从文件夹拖字幕文件上去，第二个总会覆盖第一个，从后面的省略号那里添加文件也是一直加不上，只能从文件夹拖到字幕文件的框里才能加上，我实在没办法了，就把两个ASS文件放在同一文件夹目录下再通过打文件名的方式试能不能加上，结果要压制了他直接给我来一句字幕文件不存在，但我两个字幕均可以正常打开，我不知道他是怎么判断我字幕文件不存在的，总之这个功能现在压根无法正常使用，求尽快完善，感激不尽。

**Comment by YohoYang** [comment]
麻烦尝试一下同时选中两个文件一起拖入，右边三个点打开的也可以直接选择多个文件，然后这样输入的路径就是多个的。
一次一个拖入拖多次确实没有支持，先试试看这样能不能满足需求

**Comment by OKtheMirror** [comment]
右边三个点打开选择的文件加不上，单个的也不行，不知道什么原因

**Comment by OKtheMirror** [comment]
同时选中两个文件一起拖入确实顺利加上了

**Comment by YohoYang** [comment]
> 右边三个点打开选择的文件加不上，单个的也不行，不知道什么原因

![20240110-162918](https://github.com/YohoYang/VSGUI/assets/16574473/c9ef3f66-5912-411c-a096-ee3fadd16c81)

我这边测试是可以的喔，你是系统是？

**Comment by OKtheMirror** [comment]
我的系统是win10

**Comment by OKtheMirror** [comment]
另外我另一个水印ASS字幕是加了循环横向滚动的特效的，结果压制进视频后就没了

**Comment by YohoYang** [comment]
> 我的系统是win10

像GIF图上那样操作没有办法框选多个么？确实不方便测试。没有复现该问题

**Comment by YohoYang** [comment]
> 另外我另一个水印ASS字幕是加了循环横向滚动的特效的，结果压制进视频后特效就没了

预览看看，估计是ass的写法兼容性问题，内置的ass解析器是libass，可以考虑加上xy-vsfilter的选项

**Comment by OKtheMirror** [comment]
按照GIF图那样框选多个加可以生效，但单个加还是不行

**Comment by YohoYang** [comment]
> 按照GIF图那样框选多个加可以生效，但单个加还是不行

是不支持一个一个加的，每次选择都会覆盖之前的。有需要我后面支持一下

**Comment by OKtheMirror** [comment]
需要后续支持单个加

**Comment by YohoYang** [comment]
> ![汉化水印 ass - 记事本 2024_1_11 0_12_08](https://private-user-images.githubusercontent.com/142728560/295630990-b46246aa-9398-44d9-8a25-3f4a9e8589eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDM1MjUsIm5iZiI6MTcwNDkwMzIyNSwicGF0aCI6Ii8xNDI3Mjg1NjAvMjk1NjMwOTkwLWI0NjI0NmFhLTkzOTgtNDRkOS04YTI1LTNmNGE5ZTg1ODllYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNjEzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzgyZDBhMGIwZmE0OGU3ZmJmYTUyM2NjNGU3N2EwYTE0ZjdlMTg2ZWY1YTRiNTk2OGMyMjkzMjRjODcyYmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J9AvV_mYy5B5hOEk9EwKl0qPmnr404lSBkSTkZnjtDg)

我的意思是在这里预览，提前检查效果。
我预计就是dll的问题，我添加一个设置到简易压制中。不过你常用的话，需求也复杂的话，简易简单的学一学vs的脚本，写vpy来处理，功能要齐全和完善不少。简易压制不可能无限的扩展功能来支持各种需求，很多东西只要自己写脚本就可以很简单的搞定。
脚本使用内置的编辑器即可打开。
![图片](https://github.com/YohoYang/VSGUI/assets/16574473/9802fc1d-019b-4bc5-91b0-bf6e408d785e)


[vpy模板.zip](https://github.com/YohoYang/VSGUI/files/13890336/vpy.zip)

**Comment by YohoYang** [comment]
已更新v1.0.6版本：
增加使用xy-vsfilter按钮，勾选后理论上你的字幕不会滚的问题可以解决
增加一次一次拖入字幕的支持
